# Build stage from Node.js image
FROM node:20-alpine as build

WORKDIR /app
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .

# Build the application
RUN pnpm build

# Production stage
FROM nginx:stable-alpine
# Copy built assets from build stage
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]